export const weatherImages = {
	'Partly cloudy': require('../assets/images/sun_little_cloud_rain.svg'),
	'Moderate rain': require('../assets/image/moderaterain.png'),
	'Patchy rain possible': require('../assets/image/moderaterain.png'),
	'Patchy rain nearby': require('../assets/image/moderaterain.png'),
	Sunny: require('../assets/image/sun.png'),
	'Clear ': require('../assets/image/sun.png'),
	Overcast: require('../assets/image/cloud.png'),
	Cloudy: require('../assets/image/cloud.png'),
	'Light rain': require('../assets/image/moderaterain.png'),
	'Moderate rain at times': require('../assets/image/moderaterain.png'),
	'Heavy rain': require('../assets/image/heavyrain.png'),
	'Heavy rain at times': require('../assets/image/heavyrain.png'),
	'Moderate or heavy freezing rain': require('../assets/image/heavyrain.png'),
	'Moderate or heavy rain shower': require('../assets/image/heavyrain.png'),
	'Moderate or heavy rain with thunder': require('../assets/image/heavyrain.png'),
	Mist: require('../assets/image/mist.png'),
	other: require('../assets/image/moderaterain.png'),
};
